function params = auv_runtime_codegen_init(cfg)
%AUV_RUNTIME_CODEGEN_INIT Nested supervisor Params from approved component inits.
% PRETARGET DEPLOY_CANDIDATE / LOGICAL COMMANDS ONLY / NOT_IN_PRODUCTION / NOT_CERTIFIED
% Compose controller/guidance/navigation/availability/FDIR; freeze scheduler/arming.
%
% TASK_ID: SUPERVISOR_INIT_RESET_001

    controller = controller_codegen_init(cfg.controller);
    guidance = guidance_codegen_init(cfg.guidance);
    navigation = nav_codegen_init();
    availability = availability_codegen_init(cfg.availability);
    fdir = rudder_fdir_codegen_init(cfg.fdir);
    safe_thrust = cfg.safe_thrust;

    tol_time = 1.0e-12;
    dt_controller = controller.dt_controller;
    dt_guidance = guidance.dt_guidance;
    dt_guidance_ctrl = guidance.dt_controller;
    dt_fdir = fdir.dt;

    timing_ok = isfinite(dt_controller) && (dt_controller > 0.0) && ...
        isfinite(dt_guidance) && (dt_guidance > 0.0) && ...
        isfinite(dt_guidance_ctrl) && (dt_guidance_ctrl > 0.0) && ...
        isfinite(dt_fdir) && (dt_fdir > 0.0) && ...
        (abs(dt_controller - 0.025) <= tol_time) && ...
        (abs(dt_fdir - 0.025) <= tol_time) && ...
        (abs(dt_controller - dt_fdir) <= tol_time) && ...
        (abs(dt_guidance_ctrl - dt_controller) <= tol_time) && ...
        (abs(dt_guidance - (3.0 * dt_controller)) <= tol_time) && ...
        (abs(dt_guidance - 0.075) <= tol_time);

    controller_limits_ok = isfinite(controller.delta_r_max) && ...
        (controller.delta_r_max > 0.0) && ...
        isfinite(controller.delta_e_max) && ...
        (controller.delta_e_max > 0.0) && ...
        isfinite(controller.thrust_max) && ...
        isfinite(controller.thrust_min) && ...
        isfinite(controller.slew_max_rad_s) && ...
        (controller.slew_max_rad_s > 0.0);

    guidance_limits_ok = isfinite(guidance.pitch_ref_max) && ...
        (guidance.pitch_ref_max > 0.0) && ...
        isfinite(guidance.pitch_ref_rate_max) && ...
        (guidance.pitch_ref_rate_max > 0.0) && ...
        isfinite(guidance.yaw_slew_max_rad_s) && ...
        (guidance.yaw_slew_max_rad_s > 0.0) && ...
        isfinite(guidance.r_ff_max_rad_s) && ...
        (guidance.r_ff_max_rad_s > 0.0);

    component_config_ok = logical(navigation.config_valid) && ...
        logical(availability.config_valid) && ...
        logical(fdir.config_valid);

    thrust_span_ok = controller.thrust_min <= controller.thrust_max;
    safe_thrust_ok = isfinite(safe_thrust) && thrust_span_ok && ...
        (safe_thrust >= controller.thrust_min) && ...
        (safe_thrust <= controller.thrust_max);

    config_valid = false;
    if timing_ok && controller_limits_ok && guidance_limits_ok && ...
            component_config_ok && safe_thrust_ok
        config_valid = true;
    end

    params = struct();
    params.controller = controller;
    params.guidance = guidance;
    params.navigation = navigation;
    params.availability = availability;
    params.fdir = fdir;
    params.safe_thrust = safe_thrust;
    params.guidance_divider = uint32(3);
    params.arm_min_healthy_ticks = uint32(3);
    params.config_valid = config_valid;
end
