# cmake/gcc-arm-none-eabi.cmake — GNU Arm Embedded toolchain for STM32F411
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(DEFINED ENV{ARM_GCC_PREFIX} AND NOT "$ENV{ARM_GCC_PREFIX}" STREQUAL "")
  set(_AUV_ARM_PREFIX "$ENV{ARM_GCC_PREFIX}")
  file(TO_CMAKE_PATH "${_AUV_ARM_PREFIX}" _AUV_ARM_PREFIX)
  if(EXISTS "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-gcc.exe")
    set(CMAKE_C_COMPILER   "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-gcc.exe")
    set(CMAKE_CXX_COMPILER "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-g++.exe")
    set(CMAKE_ASM_COMPILER "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-gcc.exe")
    set(CMAKE_OBJCOPY      "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-objcopy.exe")
    set(CMAKE_OBJDUMP      "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-objdump.exe")
    set(CMAKE_SIZE         "${_AUV_ARM_PREFIX}/bin/arm-none-eabi-size.exe")
  elseif(EXISTS "${_AUV_ARM_PREFIX}/arm-none-eabi-gcc.exe")
    set(CMAKE_C_COMPILER   "${_AUV_ARM_PREFIX}/arm-none-eabi-gcc.exe")
    set(CMAKE_CXX_COMPILER "${_AUV_ARM_PREFIX}/arm-none-eabi-g++.exe")
    set(CMAKE_ASM_COMPILER "${_AUV_ARM_PREFIX}/arm-none-eabi-gcc.exe")
    set(CMAKE_OBJCOPY      "${_AUV_ARM_PREFIX}/arm-none-eabi-objcopy.exe")
    set(CMAKE_OBJDUMP      "${_AUV_ARM_PREFIX}/arm-none-eabi-objdump.exe")
    set(CMAKE_SIZE         "${_AUV_ARM_PREFIX}/arm-none-eabi-size.exe")
  else()
    set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
    set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
    set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
    set(CMAKE_OBJCOPY      arm-none-eabi-objcopy)
    set(CMAKE_OBJDUMP      arm-none-eabi-objdump)
    set(CMAKE_SIZE         arm-none-eabi-size)
  endif()
else()
  set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
  set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
  set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
  set(CMAKE_OBJCOPY      arm-none-eabi-objcopy)
  set(CMAKE_OBJDUMP      arm-none-eabi-objdump)
  set(CMAKE_SIZE         arm-none-eabi-size)
endif()

set(CMAKE_C_FLAGS_INIT   "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb")
set(CMAKE_CXX_FLAGS_INIT "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb")
set(CMAKE_ASM_FLAGS_INIT "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
