function out = auv_simulation_category_registry(request, category_id)
%AUV_SIMULATION_CATEGORY_REGISTRY  Read-only category registry for AUV V1 artifacts.
%   registry = auv_simulation_category_registry()
%   ids = auv_simulation_category_registry('categories')
%   names = auv_simulation_category_registry('declared_metrics', category_id)
%   entry = auv_simulation_category_registry('resolve', category_id)
%   entry = auv_simulation_category_registry(category_id)

    if nargin >= 1 && ischar(request) && strcmpi(request, 'categories')
        out = category_ids();
        return;
    end

    if nargin >= 2 && ischar(request) && strcmpi(request, 'resolve')
        out = resolve_category(category_id);
        return;
    end

    if nargin >= 2 && ischar(request) && strcmpi(request, 'declared_metrics')
        out = declared_metrics(category_id);
        return;
    end

    if nargin == 1 && ischar(request) && ~strcmpi(request, 'categories')
        out = resolve_category(request);
        return;
    end

    registry = struct();
    registry.schema = 'auv_v1_simulation_category_registry_v1';
    registry.version = '1.0.0';
    registry.matlab_release = 'R2025b';
    registry.contract_schema = 'auv_v1_shared_result_contract_v1';
    registry.contract_version = '1.0.0';
    registry.categories = build_category_table();
    out = registry;
end

function ids = category_ids()
    ids = { ...
        'nominal', ...
        'bounded_current', ...
        'sensor_noise_dropout', ...
        'actuator_limits', ...
        'passive_roll_stress', ...
        'roll_rate_solution_audit'};
end

function names = declared_metrics(category_id)
    entry = resolve_category(category_id);
    names = sort(fieldnames(entry.units));
end

function entry = resolve_category(category_id)
    if nargin < 1 || isempty(category_id) || ~ischar(category_id) && ~isstring(category_id)
        error('auv_simulation_category_registry:InvalidCategory', ...
            'category_id must be a non-empty string');
    end
    category_id = char(category_id);
    table = build_category_table();
    for i = 1:numel(table)
        if strcmp(table(i).category_id, category_id)
            entry = table(i);
            return;
        end
    end
    error('auv_simulation_category_registry:UnknownCategory', ...
        'unknown simulation category: %s', category_id);
end

function table = build_category_table()
    shared = auv_result_contract();
    table = [ ...
        build_entry( ...
            'nominal', ...
            'Nominal 3D straight-line baseline', ...
            'robustness_v1', ...
            'path_metrics_rollup', ...
            'auv_v1_nominal_baseline_v1', ...
            'artifacts/robustness/nominal.json', ...
            nominal_units()), ...
        build_entry( ...
            'bounded_current', ...
            'Bounded-current straight-line envelope', ...
            'robustness_v1', ...
            'path_metrics_rollup', ...
            'auv_v1_bounded_current_v1', ...
            'artifacts/robustness/bounded_current.json', ...
            bounded_current_units()), ...
        build_entry( ...
            'sensor_noise_dropout', ...
            'Sensor noise and short-dropout characterization', ...
            'robustness_v1', ...
            'path_metrics_rollup', ...
            'auv_v1_sensor_noise_dropout_v1', ...
            'artifacts/robustness/sensor_noise_dropout.json', ...
            sensor_units()), ...
        build_entry( ...
            'actuator_limits', ...
            'Actuator magnitude, rate and deadband limits', ...
            'robustness_v1', ...
            'path_metrics_rollup', ...
            'auv_v1_actuator_limits_v1', ...
            'artifacts/robustness/actuator_limits.json', ...
            actuator_units()), ...
        build_entry( ...
            'passive_roll_stress', ...
            'Passive roll stress matrix (SIM9)', ...
            'robustness_v2', ...
            'roll_stress_rollup', ...
            'auv_v1_passive_roll_stress_v1', ...
            'artifacts/robustness_v2/passive_roll_stress.json', ...
            roll_units(shared)), ...
        build_entry( ...
            'roll_rate_solution_audit', ...
            'Roll-rate solution audit with shadow catalog (SIM10)', ...
            'robustness_v2', ...
            'roll_audit_rollup', ...
            'auv_v1_roll_rate_solution_audit_v1', ...
            'artifacts/robustness_v2/roll_rate_solution_audit.json', ...
            roll_units(shared))];
end

function entry = build_entry(category_id, label, family, artifact_kind, source_schema, artifact_path, units)
    entry = struct();
    entry.category_id = category_id;
    entry.label = label;
    entry.family = family;
    entry.artifact_kind = artifact_kind;
    entry.source_schema = source_schema;
    entry.artifact_path = artifact_path;
    entry.units = units;
end

function units = nominal_units()
    units = struct( ...
        'duration_s', 's', ...
        'dt', 's', ...
        'seed', 'unitless', ...
        'mean_cross_track', 'm', ...
        'max_cross_track', 'm', ...
        'mean_yaw_err_deg', 'deg', ...
        'mean_pitch_err_deg', 'deg', ...
        'pitch_chatter_dps', 'deg/s', ...
        'theta_pp_deg', 'deg', ...
        'pct_samples_overrun', 'percent');
end

function units = bounded_current_units()
    units = nominal_units();
    units.Vc_ned = 'm/s';
end

function units = sensor_units()
    units = nominal_units();
    units.nav_dt_base = 's';
    units.imu_gyro_sigma_rad_s = 'rad/s';
    units.imu_accel_sigma_mps2 = 'm/s^2';
    units.depth_sigma_m = 'm';
    units.rmse_depth_m = 'm';
    units.rmse_yaw_deg = 'deg';
    units.avail_pct = 'percent';
end

function units = actuator_units()
    units = nominal_units();
    units.de_max_deg = 'deg';
    units.dr_max_deg = 'deg';
    units.rate_dps = 'deg/s';
    units.sat_frac = 'unitless';
    units.deadband_deg = 'deg';
    units.elevator_mag_sat_pct = 'percent';
    units.rudder_mag_sat_pct = 'percent';
end

function units = roll_units(contract)
    units = struct( ...
        'duration_s', 's', ...
        'dt', 's', ...
        'seed', 'unitless', ...
        'runtime_s', 's');
    thr = contract.screening.threshold_units;
    thr_fields = fieldnames(thr);
    for i = 1:numel(thr_fields)
        units.(thr_fields{i}) = thr.(thr_fields{i});
    end
    met = contract.metrics.units;
    met_fields = fieldnames(met);
    for i = 1:numel(met_fields)
        units.(met_fields{i}) = met.(met_fields{i});
    end
end
