function write_auv_v1_acceptance_draft()
%WRITE_AUV_V1_ACCEPTANCE_DRAFT  Draft acceptance envelope from robustness artifacts.
%   Reads five measured simulation JSON artifacts, validates certified=false and
%   zero failing executions, extracts nominal and worst-case metrics, and writes
%   artifacts/robustness/acceptance_draft.json for human milestone review only.

    marginFrac = 0.25;
    repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    artDir = fullfile(repoRoot, 'artifacts', 'robustness');

    artifactNames = { ...
        'nominal.json', ...
        'bounded_current.json', ...
        'sensor_noise_dropout.json', ...
        'actuator_limits.json', ...
        'combined_summary.json'};
    artifacts = struct();
    for i = 1:numel(artifactNames)
        name = artifactNames{i};
        path = fullfile(artDir, name);
        if ~isfile(path)
            error('write_auv_v1_acceptance_draft:MissingArtifact', ...
                'Required artifact missing: %s', path);
        end
        raw = fileread(path);
        artifacts.(matlab.lang.makeValidName(erase(name, '.json'))) = jsondecode(raw);
    end

    combined = artifacts.combined_summary;
    assertCertifiedFalse(combined, 'combined_summary.json');
    assertCertifiedFalse(artifacts.nominal, 'nominal.json');
    assertCertifiedFalse(artifacts.bounded_current, 'bounded_current.json');
    assertCertifiedFalse(artifacts.sensor_noise_dropout, 'sensor_noise_dropout.json');
    assertCertifiedFalse(artifacts.actuator_limits, 'actuator_limits.json');

    if ~isfield(combined, 'failing_executions') || ~isempty(combined.failing_executions)
        error('write_auv_v1_acceptance_draft:FailingExecutions', ...
            'combined_summary.failing_executions must be empty.');
    end

    nominalPath = extractNominalPathMetrics(artifacts.nominal, combined);
    nominalNav = extractNominalNavMetrics(artifacts.sensor_noise_dropout);
    nominalAct = extractNominalActuatorMetrics(artifacts.actuator_limits);

    worstPath = extractWorstPathMetrics(combined.worst_case);
    worstNav = extractWorstNavMetrics(combined.worst_case);
    worstAct = extractWorstActuatorMetrics(combined.worst_case);

    thresholds = struct();
    thresholds.mean_cte_perp = buildThreshold( ...
        'path', nominalPath.mean_cte_perp, combined.worst_case.mean_cte_perp, ...
        marginFrac, 'combined_summary.worst_case.mean_cte_perp.value');
    thresholds.max_cte_perp = buildThreshold( ...
        'path', nominalPath.max_cte_perp, combined.worst_case.max_cte_perp, ...
        marginFrac, 'combined_summary.worst_case.max_cte_perp.value');
    thresholds.mean_yaw_err_deg = buildThreshold( ...
        'path', nominalPath.mean_yaw_err_deg, combined.worst_case.mean_yaw_err_deg, ...
        marginFrac, 'combined_summary.worst_case.mean_yaw_err_deg.value');
    thresholds.pitch_chatter_dps = buildThreshold( ...
        'path', nominalPath.pitch_chatter_dps, combined.worst_case.pitch_chatter_dps, ...
        marginFrac, 'combined_summary.worst_case.pitch_chatter_dps.value');
    thresholds.elevator_mag_sat_pct = buildThreshold( ...
        'actuator', nominalAct.elevator_mag_sat_pct, combined.worst_case.elevator_mag_sat_pct, ...
        marginFrac, 'combined_summary.worst_case.elevator_mag_sat_pct.value');
    thresholds.rudder_mag_sat_pct = buildThreshold( ...
        'actuator', nominalAct.rudder_mag_sat_pct, combined.worst_case.rudder_mag_sat_pct, ...
        marginFrac, 'combined_summary.worst_case.rudder_mag_sat_pct.value');
    thresholds.elevator_cmd_rmse_deg = buildThreshold( ...
        'actuator', nominalAct.elevator_cmd_rmse_deg, combined.worst_case.elevator_cmd_rmse_deg, ...
        marginFrac, 'combined_summary.worst_case.elevator_cmd_rmse_deg.value');
    thresholds.nav_rmse_pos_abs_norm_m = buildThreshold( ...
        'navigation', nominalNav.rmse_pos_abs_norm_m, combined.worst_case.nav_rmse_pos_abs_norm_m, ...
        marginFrac, 'combined_summary.worst_case.nav_rmse_pos_abs_norm_m.value');
    thresholds.nav_rmse_depth_m = buildThreshold( ...
        'navigation', nominalNav.rmse_depth_m, combined.worst_case.nav_rmse_depth_m, ...
        marginFrac, 'combined_summary.worst_case.nav_rmse_depth_m.value');
    thresholds.nav_rmse_yaw_deg = buildThreshold( ...
        'navigation', nominalNav.rmse_yaw_deg, combined.worst_case.nav_rmse_yaw_deg, ...
        marginFrac, 'combined_summary.worst_case.nav_rmse_yaw_deg.value');
    thresholds.nav_max_pos_rel_norm_m = buildThreshold( ...
        'navigation', nominalNav.max_pos_rel_norm_m, combined.worst_case.nav_max_pos_rel_norm_m, ...
        marginFrac, 'combined_summary.worst_case.nav_max_pos_rel_norm_m.value');

    draft = struct();
    draft.schema = 'auv_v1_acceptance_envelope_draft_v1';
    draft.approved = false;
    draft.certified = false;
    draft.generated_utc = char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''));
    draft.source_artifacts = cellfun(@(n) fullfile(artDir, n), artifactNames, 'UniformOutput', false);
    draft.prerequisites = struct( ...
        'all_source_certified_false', true, ...
        'failing_executions_count', 0, ...
        'combined_matrix_caps', combined.matrix_caps);
    draft.nominal = struct('path', nominalPath, 'navigation', nominalNav, 'actuator', nominalAct);
    draft.worst_case = struct('path', worstPath, 'navigation', worstNav, 'actuator', worstAct);
    draft.proposed_thresholds = thresholds;
    draft.note = ['Draft acceptance envelope derived from measured simulation artifacts only. ', ...
        'Proposed thresholds are not approved, not certified, and do not constitute a vehicle PASS.'];

    outPath = fullfile(artDir, 'acceptance_draft.json');
    outDir = fileparts(outPath);
    if ~isfolder(outDir)
        mkdir(outDir);
    end
    fid = fopen(outPath, 'w');
    if fid < 0
        error('write_auv_v1_acceptance_draft:WriteFailed', 'Cannot open %s for writing.', outPath);
    end
    cleaner = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(draft));
    fprintf('Wrote %s\n', outPath);
end

function assertCertifiedFalse(artifact, label)
    if ~isfield(artifact, 'certified') || artifact.certified ~= false
        error('write_auv_v1_acceptance_draft:CertifiedNotFalse', ...
            '%s must have certified=false.', label);
    end
end

function metrics = extractNominalPathMetrics(nominal, combined)
    if isfield(combined, 'nominal_metrics')
        src = combined.nominal_metrics;
    elseif isfield(nominal, 'metrics')
        src = nominal.metrics;
    else
        error('write_auv_v1_acceptance_draft:MissingNominalPath', ...
            'No nominal path metrics found.');
    end
    metrics = struct( ...
        'mean_cte_perp', src.mean_cte_perp, ...
        'max_cte_perp', src.max_cte_perp, ...
        'mean_yaw_err_deg', src.mean_yaw_err_deg, ...
        'pitch_chatter_dps', src.pitch_chatter_dps, ...
        'mean_abs_es', src.mean_abs_es, ...
        'max_cross_track', src.max_cross_track);
end

function metrics = extractNominalNavMetrics(sensorArtifact)
    caseMetrics = findCaseMetrics(sensorArtifact.cases, 'declared_finite_noise');
    metrics = struct( ...
        'rmse_pos_abs_norm_m', caseMetrics.rmse_pos_abs_norm_m, ...
        'rmse_depth_m', caseMetrics.rmse_depth_m, ...
        'rmse_yaw_deg', caseMetrics.rmse_yaw_deg, ...
        'max_pos_rel_norm_m', caseMetrics.max_pos_rel_norm_m, ...
        'avail_pct', caseMetrics.avail_pct, ...
        'integrity_pass', caseMetrics.integrity_pass);
end

function metrics = extractNominalActuatorMetrics(actuatorArtifact)
    caseAct = findActuatorCase(actuatorArtifact.cases, 'ideal');
    metrics = struct( ...
        'elevator_mag_sat_pct', caseAct.elevator_mag_sat_pct, ...
        'rudder_mag_sat_pct', caseAct.rudder_mag_sat_pct, ...
        'elevator_cmd_rmse_deg', caseAct.elevator_cmd_rmse_deg, ...
        'rudder_cmd_rmse_deg', caseAct.rudder_cmd_rmse_deg, ...
        'elevator_rate_dwell_pct', caseAct.elevator_rate_dwell_pct, ...
        'rudder_rate_dwell_pct', caseAct.rudder_rate_dwell_pct);
end

function metrics = extractWorstPathMetrics(worstCase)
    metrics = struct( ...
        'mean_cte_perp', worstCase.mean_cte_perp, ...
        'max_cte_perp', worstCase.max_cte_perp, ...
        'mean_yaw_err_deg', worstCase.mean_yaw_err_deg, ...
        'pitch_chatter_dps', worstCase.pitch_chatter_dps, ...
        'nominal_mean_cte_perp', worstCase.nominal_mean_cte_perp);
end

function metrics = extractWorstNavMetrics(worstCase)
    metrics = struct( ...
        'nav_rmse_pos_abs_norm_m', worstCase.nav_rmse_pos_abs_norm_m, ...
        'nav_rmse_depth_m', worstCase.nav_rmse_depth_m, ...
        'nav_rmse_yaw_deg', worstCase.nav_rmse_yaw_deg, ...
        'nav_max_pos_rel_norm_m', worstCase.nav_max_pos_rel_norm_m);
end

function metrics = extractWorstActuatorMetrics(worstCase)
    metrics = struct( ...
        'elevator_mag_sat_pct', worstCase.elevator_mag_sat_pct, ...
        'rudder_mag_sat_pct', worstCase.rudder_mag_sat_pct, ...
        'elevator_cmd_rmse_deg', worstCase.elevator_cmd_rmse_deg);
end

function entry = buildThreshold(category, nominalValue, worstEntry, marginFrac, sourceMetric)
    worstValue = worstEntry.value;
    marginAbs = worstValue * marginFrac;
    proposed = worstValue * (1 + marginFrac);
    entry = struct( ...
        'category', category, ...
        'source_metric', sourceMetric, ...
        'formula', 'proposed_threshold = worst_case_value * (1 + margin_frac)', ...
        'margin_frac', marginFrac, ...
        'margin_abs', marginAbs, ...
        'nominal_value', nominalValue, ...
        'worst_case_value', worstValue, ...
        'worst_case_case_id', worstEntry.case_id, ...
        'proposed_threshold', proposed);
end

function metrics = findCaseMetrics(cases, targetName)
    for i = 1:numel(cases)
        if strcmp(cases(i).name, targetName)
            metrics = cases(i).metrics;
            return;
        end
    end
    error('write_auv_v1_acceptance_draft:MissingNavCase', ...
        'Navigation case not found: %s', targetName);
end

function actuatorMetrics = findActuatorCase(cases, targetName)
    for i = 1:numel(cases)
        if strcmp(cases(i).name, targetName)
            actuatorMetrics = cases(i).actuator_metrics;
            return;
        end
    end
    error('write_auv_v1_acceptance_draft:MissingActuatorCase', ...
        'Actuator case not found: %s', targetName);
end
